
package com.sltc.soa.client.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DemoWS", targetNamespace = "http://soa.sltc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DemoWS {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transfer", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.Transfer")
    @ResponseWrapper(localName = "transferResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.TransferResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/transferRequest", output = "http://soa.sltc.com/DemoWS/transferResponse")
    public float transfer(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deposit", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.Deposit")
    @ResponseWrapper(localName = "depositResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.DepositResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/depositRequest", output = "http://soa.sltc.com/DemoWS/depositResponse")
    public float deposit(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.AddUserResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/addUserRequest", output = "http://soa.sltc.com/DemoWS/addUserResponse")
    public boolean addUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userChecking", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.UserChecking")
    @ResponseWrapper(localName = "userCheckingResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.UserCheckingResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/userCheckingRequest", output = "http://soa.sltc.com/DemoWS/userCheckingResponse")
    public boolean userChecking(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "withdraw", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.Withdraw")
    @ResponseWrapper(localName = "withdrawResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.WithdrawResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/withdrawRequest", output = "http://soa.sltc.com/DemoWS/withdrawResponse")
    public float withdraw(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "substraction", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.Substraction")
    @ResponseWrapper(localName = "substractionResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.SubstractionResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/substractionRequest", output = "http://soa.sltc.com/DemoWS/substractionResponse")
    public int substraction(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "balanceChecking", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.BalanceChecking")
    @ResponseWrapper(localName = "balanceCheckingResponse", targetNamespace = "http://soa.sltc.com/", className = "com.sltc.soa.client.stub.BalanceCheckingResponse")
    @Action(input = "http://soa.sltc.com/DemoWS/balanceCheckingRequest", output = "http://soa.sltc.com/DemoWS/balanceCheckingResponse")
    public float balanceChecking(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
